# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-20 17:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentDailyDish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='DailyDish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nazwa dania')),
                ('description', models.TextField(verbose_name='Opis dania')),
            ],
        ),
        migrations.CreateModel(
            name='Musician',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('link', models.CharField(max_length=255)),
                ('photo_link', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='currentdailydish',
            name='current_dish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='odessaapp.DailyDish'),
        ),
    ]
